[env]
TERM = "xterm-256color"

[font]
size = 14
offset = { x = 2, y = 14 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding.x = 30
padding.y = 20

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]
